project:
  title: "nso-24-stats"
  type: website
  output-dir: ../docs

format:
  html:
    theme: quartz

website:
  title: "Oh God—<br/>not the math"
  page-navigation: false

  site-url: https://maxinelevesque.github.io/nso-24-stats/
  repo-url: https://github.com/maxinelevesque/nso-24-stats
  repo-subdir: slides
  repo-actions: [source, issue]

  sidebar:
    style: floating
    contents:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda