# Protips

## This site

This site was made with [Quarto](https://quarto.org) and hosted on [GitHub Pages](https://pages.github.com). You should try them both for your projects—they're rad!

#### Search
The search bar can find anything on this site or in any of the slide presentations; try it by pressing `S`!

#### Code
You can find the code for this site and all slide decks on [GitHub](https://github.org/maxinelevesque/nso-24-stats).

All code blocks for figures and demonstrations are actually executed each time the entire site and all the slide decks are rendered to HTML; this means that each time you view the site yourself from your own machine, you'll get a new random result for everything!

## Slides

Slides are revendered with [Reveal.js](https://revealjs.com) at build-time.

When you're in a slide presentation:

* Press `SPACE` to advance to the next slide; or, use the left and right arrow keys to go back and forth between slides. On mobile, swipe left or right.
* Press `ESC` or `O` to show the grid overview; slides within a section advance going down, and sections are arranged left-to-right.
* Press `F` to enter fullscreen mode.